#!/bin/sh

# This is used for Linux platform, get the ip address by ifconfig

if [ $# != 2 ]; then
    echo "usage: getip interface protocol" > /dev/stderr;
    echo " - interface: eth0 or wlan0 or ..." > /dev/stderr;
    echo " - protocol: ipv4 or ipv6" > /dev/stderr;
    echo " - example: getip eth0 ipv4" > /dev/stderr;
    exit 1
fi

interface=$1
protocol=$2

if [ "$protocol" = "ipv4" ]; then
    protocol="inet addr";

    ifconfig $interface | grep "$protocol" | awk '{print $2}' | awk -F ':' '{print $2}'
elif [ "$protocol" = "ipv6" ]; then
    protocol="inet6 addr";

    ifconfig $interface | grep "$protocol" | awk '{print $3}' | awk -F '/' '{print $1}'
else
    echo "unknow protocol, please input ipv4 or ipv6" > /dev/stderr;
    exit 1
fi

